name: Sync Google Sheet to JSON

# schedule (UTC) + manual trigger
on:
  schedule:
    - cron: "0 * * * *"    # every hour (UTC). Change if you want different frequency.
  workflow_dispatch: {}

# allow the action to push commits
permissions:
  contents: write

jobs:
  sync-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth

      - name: Write Google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          printf '%s' "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Export Google Sheet -> JSON
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}   # optional; remove and hardcode below if you prefer
        run: |
          python <<'PY'
          import os, json
          from google.oauth2.service_account import Credentials
          import gspread

          # config
          sheet_id = os.environ.get("SHEET_ID") or "<YOUR_SHEET_ID>"
          scopes = [
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
          ]

          # authenticate
          creds = Credentials.from_service_account_file("credentials.json", scopes=scopes)
          client = gspread.authorize(creds)

          # open and read all sheets
          sh = client.open_by_key(sheet_id)
          out = {}
          for ws in sh.worksheets():
              out[ws.title] = ws.get_all_records()

          # write JSON
          with open("test.json", "w", encoding="utf-8") as f:
              json.dump(out, f, indent=2, ensure_ascii=False)
          print("Wrote test.json with sheets:", ", ".join(out.keys()))
          PY

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test.json
          git diff --cached --quiet || (git commit -m "chore: update test.json from Google Sheet" && git push)
